// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDApQ0EWUDoGJsH5J9Kwfz-rArgMWh_uqc',
    appId: '1:80998489252:web:9117f1ed30d8fff0ef9a31',
    messagingSenderId: '80998489252',
    projectId: 'uber-eats-ff842',
    authDomain: 'uber-eats-ff842.firebaseapp.com',
    storageBucket: 'uber-eats-ff842.appspot.com',
    measurementId: 'G-BTFD0L8VFZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHXCsKdRErOLmTpPQK3vitnuhsWYaPMQw',
    appId: '1:80998489252:android:33c893fb142ecf21ef9a31',
    messagingSenderId: '80998489252',
    projectId: 'uber-eats-ff842',
    storageBucket: 'uber-eats-ff842.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDy4Y0Y9DKj0ojzzPIfvtz2jM5emfsSN7k',
    appId: '1:80998489252:ios:c94e2a7c7cf99562ef9a31',
    messagingSenderId: '80998489252',
    projectId: 'uber-eats-ff842',
    storageBucket: 'uber-eats-ff842.appspot.com',
    iosBundleId: 'com.example.ubereatsresturant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDy4Y0Y9DKj0ojzzPIfvtz2jM5emfsSN7k',
    appId: '1:80998489252:ios:d72d1e0699d007c3ef9a31',
    messagingSenderId: '80998489252',
    projectId: 'uber-eats-ff842',
    storageBucket: 'uber-eats-ff842.appspot.com',
    iosBundleId: 'com.example.ubereats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDApQ0EWUDoGJsH5J9Kwfz-rArgMWh_uqc',
    appId: '1:80998489252:web:bde554baac356f81ef9a31',
    messagingSenderId: '80998489252',
    projectId: 'uber-eats-ff842',
    authDomain: 'uber-eats-ff842.firebaseapp.com',
    storageBucket: 'uber-eats-ff842.appspot.com',
    measurementId: 'G-Q39092F92J',
  );
}